#!/usr/bin/env python3
"""
Generate CONTRIBUTORS.md from git commit history.

This script extracts contributor information from git and creates/updates
the CONTRIBUTORS.md file with commit statistics.

Usage:
    python scripts/generate_contributors.py
"""

import subprocess
import re
from datetime import datetime


def run_git_command(cmd):
    """Run a git command and return output."""
    result = subprocess.run(cmd, shell=True, capture_output=True, text=True, check=True)
    return result.stdout.strip()


def get_contributors():
    """Get list of contributors with commit counts."""
    # Get commit counts per author
    shortlog = run_git_command("git shortlog -sn --all --no-merges")

    contributors = []
    for line in shortlog.split("\n"):
        if line.strip():
            match = re.match(r"\s*(\d+)\s+(.+)", line)
            if match:
                commits = int(match.group(1))
                name = match.group(2)
                contributors.append({"name": name, "commits": commits})

    return contributors


def get_contributor_details(name):
    """Get email and first commit date for a contributor."""
    # Get email
    email_cmd = f"git log --author='{name}' --format='%aE' | head -1"
    try:
        email = run_git_command(email_cmd)
    except Exception:
        email = ""

    # Get first commit date
    date_cmd = f"git log --author='{name}' --format='%aI' --reverse | head -1"
    try:
        date_str = run_git_command(date_cmd)
        date = datetime.fromisoformat(date_str.replace("Z", "+00:00"))
        first_commit = date.strftime("%B %Y")
    except Exception:
        first_commit = "Unknown"

    return email, first_commit


def get_github_username(email):
    """Try to extract GitHub username from email or commits."""
    # Try to get GitHub username from commit
    cmd = f"git log --author='{email}' --format='%an' | head -1"
    try:
        return run_git_command(cmd)
    except Exception:
        return None


def generate_contributors_md(contributors):
    """Generate CONTRIBUTORS.md content."""

    content = [
        "# Contributors 🙏",
        "",
        (
            "This file lists all contributors to **py-googletraffic**. "
            "We appreciate every contribution!"
        ),
        "",
        "## Core Contributors",
        "",
        "The following people have contributed to this project, sorted by number of commits:",
        "",
        "| Contributor | Commits | First Contribution |",
        "|-------------|---------|-------------------|",
    ]

    # Add each contributor
    for contrib in contributors:
        name = contrib["name"]
        commits = contrib["commits"]
        email, first_commit = get_contributor_details(name)

        # Format name (try to make it a GitHub link if possible)
        if email and "noreply.github.com" in email:
            # Extract GitHub username from noreply email
            username = email.split("@")[0].split("+")[-1]
            name_link = f"[@{username}](https://github.com/{username})"
        else:
            name_link = name

        content.append(f"| {name_link} | {commits} | {first_commit} |")

    content.extend(
        [
            "",
            "## How to Contribute",
            "",
            "We welcome contributions from everyone! Here's how you can help:",
            "",
            "- 🐛 **Report bugs** - Open an issue describing the problem",
            "- 💡 **Suggest features** - Share your ideas for improvements",
            "- 📝 **Improve documentation** - Fix typos, clarify instructions, add examples",
            "- 🔧 **Submit code** - Fix bugs, add features, improve performance",
            "- 🧪 **Write tests** - Increase test coverage",
            "- 🎨 **Share examples** - Show interesting use cases",
            "",
            "See [CONTRIBUTING.md](CONTRIBUTING.md) for detailed contribution guidelines.",
            "",
            "## Recognition",
            "",
            "All contributors are:",
            "- Listed on this page",
            (
                "- Shown on the [GitHub repository contributors page]"
                "(https://github.com/yourusername/py-googletraffic/graphs/contributors)"
            ),
            "- Credited in release notes for their contributions",
            "",
            "## Updating This File",
            "",
            "This file is automatically generated from git commit history. To update it:",
            "",
            "```bash",
            "python scripts/generate_contributors.py",
            "```",
            "",
            "Or use the GitHub Action which updates it automatically on each push to main.",
            "",
            "---",
            "",
            f"*Last updated: {datetime.now().strftime('%Y-%m-%d')}*",
            f"*Total contributors: {len(contributors)}*",
            f"*Total commits: {sum(c['commits'] for c in contributors)}*",
        ]
    )

    return "\n".join(content)


def main():
    """Main function."""
    print("📊 Analyzing git history...")

    # Get contributors
    contributors = get_contributors()
    print(f"✅ Found {len(contributors)} contributor(s)")

    # Generate content
    print("📝 Generating CONTRIBUTORS.md...")
    content = generate_contributors_md(contributors)

    # Write file
    with open("CONTRIBUTORS.md", "w", encoding="utf-8") as f:
        f.write(content)

    print("✅ CONTRIBUTORS.md updated successfully!")
    print("\nContributors:")
    for contrib in contributors:
        print(f"  - {contrib['name']}: {contrib['commits']} commit(s)")


if __name__ == "__main__":
    main()
